Repository nod-ai/shark-ui, pull requests merged in 2025-07, with the labels that each got.

#449 refactor(library/URI): preps results of component parsing for extraction
  src/library/customTypes/UniformResourceIdentifier/index.ts
Labels: refactor

#448 refactor(library/URI): separates component parsing from instantiation
  src/library/customTypes/UniformResourceIdentifier/index.ts
Labels: refactor

#447 refactor(library/URI): preps force unwraps to be converted to guards
  src/library/customTypes/UniformResourceIdentifier/index.ts
Labels: refactor

#451 refactor: preps subjects of guards against force unwraps
  src/library/Base64CharacterEncodedByteSequence.ts
  src/library/customTypes/UniformResourceIdentifier/Data/MediaType/index.ts
  src/library/customTypes/UniformResourceIdentifier/index.ts
Labels: refactor

#457 fix(library/URI): adds missing call to `.unwrapped`
  src/library/customTypes/UniformResourceIdentifier/index.ts
Labels: fix

#456 refactor(library/Byte): avoids imports that could become circular
  src/library/Byte/Sequence/EncodingCompatibilityError.ts
  src/library/Byte/Sequence/index.ts
  src/library/Byte/index.ts
  src/library/Byte/utilities/cofactorTo.ts
Labels: refactor

#455 refactor(library/Byte): streamlines exports
  src/library/Base64CharacterEncodedByteSequence.ts
  src/library/Byte/exports.ts
  src/library/Byte/index.ts
Labels: refactor

#458 refactor: clarifies intent when returning new instances from some scope
  src/library/WebAPI/Server.ts
  src/library/customTypes/UniformResourceIdentifier/Data/Image/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/MediaType/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/index.ts
  src/library/customTypes/UniformResourceIdentifier/index.ts
  src/utilities/Repository.ts
Labels: refactor

#461 refactor(library/URI): highlights parsed components
  src/library/customTypes/UniformResourceIdentifier/Data/Image/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/index.ts
Labels: refactor

#411 refactor(library/Base64CharacterEncodedByteSequence): propagates parsing errors safely
  src/features/TextToImage/models/SDXL/client/conversions/StabilityAI_Client_Image.ts
  src/library/Base64CharacterEncodedByteSequence/index.ts
  src/library/ShimmedStabilityAIClient/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/index.ts
Labels: refactor

#468 linter(cypress): centralizes configuration
  cypress/eslint.config.ts
  cypress/package.d.ts
  cypress/tsconfig.json
  eslint.config.ts
  tsconfig.node.json
Labels: linter

#478 refactor(library/typeUtilities): removes suite of unsafe string parsers
  src/library/typeUtilities/ForcibleStringParser.ts
  src/library/typeUtilities/StaticForcibleStringParser.ts
  src/library/typeUtilities/StringForciblyParsable.ts
Labels: refactor

#479 fix(library/URI): avoids serializing non-conformant encodings
  src/library/customTypes/UniformResourceIdentifier/Data/index.ts
Labels: fix

#484 ci(node): adds code compilation to workflow
  .github/workflows/node.yml
Labels: ci

#486 refactor: preserves intent of named re-exports
  src/library/HTTP/Request/index.ts
  src/library/HTTP/Response/index.ts
Labels: refactor

#487 refactor(library/MediaType): un-nests directory from URI library
  src/library/MediaType/StructuredSyntaxNameSuffix/Any.ts
  src/library/MediaType/StructuredSyntaxNameSuffix/all.ts
  src/library/MediaType/StructuredSyntaxNameSuffix/exports.ts
  src/library/MediaType/StructuredSyntaxNameSuffix/index.ts
  src/library/MediaType/TopLevel/Any.ts
  src/library/MediaType/TopLevel/Composite/Any.ts
  src/library/MediaType/TopLevel/Composite/all.ts
  src/library/MediaType/TopLevel/Composite/exports.ts
  src/library/MediaType/TopLevel/Composite/index.ts
  src/library/MediaType/TopLevel/Discrete/Any.ts
  src/library/MediaType/TopLevel/Discrete/all.ts
  src/library/MediaType/TopLevel/Discrete/exports.ts
  src/library/MediaType/TopLevel/Discrete/index.ts
  src/library/MediaType/TopLevel/exports.ts
  src/library/MediaType/TopLevel/index.ts
  src/library/MediaType/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/Image/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/index.ts
Labels: refactor

#494 refactor(library/vue): ensures all imports are behind facade
  eslint.import.ts
  src/components/DiscreteSlider.vue
  src/components/NavigationPanel.vue
  src/features/TextToImage/components/TextToImageInputSection.vue
  src/library/vue/index.ts
  src/library/vue/reactivity.ts
  src/library/vue/statefulAttempt.ts
  src/main.ts
  src/pages/TextToImagePage.vue
  src/shims-vue.d.ts
Labels: refactor

#493 refactor: avoids misuse of "underscore prefix" convention
  src/library/ShimmedStabilityAIClient/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/index.ts
  src/library/customTypes/UniformResourceIdentifier/index.ts
Labels: refactor

#496 refactor: avoids destructuring within parameter-property-eligible constructors
  src/library/HTTP/Client.ts
  src/library/ShimmedStabilityAIClient/index.ts
Labels: refactor

#498 ci(conventional-commit): adds "style" commit type
  .github/workflows/conventional-commit.yml
Labels: ci

#497 style: ensures multiline parameters in constructors
  src/features/TextToImage/config/utilities/DynamicConfig/FetchingError.ts
  src/features/TextToImage/config/utilities/StaticConfig/StaticConfigReadingError.ts
  src/library/Byte/Sequence/EncodingCompatibilityError.ts
  src/library/HTTP/Endpoint/ResponseError.ts
  src/library/customTypes/NonTrivialString/ParsingError.ts
Labels: style

#491 refactor: prefers parameter properties
  src/library/HTTP/Client.ts
  src/library/HTTP/Endpoint/ResponseError.ts
  src/library/customTypes/UniformResourceIdentifier/Data/Image/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/index.ts
  src/library/customTypes/UniformResourceIdentifier/index.ts
Labels: refactor

#488 refactor(library/ContentDescriptor): renames concept from "media type"
  src/library/ContentDescriptor/StructuredSyntaxNameSuffix/Any.ts
  src/library/ContentDescriptor/StructuredSyntaxNameSuffix/all.ts
  src/library/ContentDescriptor/StructuredSyntaxNameSuffix/exports.ts
  src/library/ContentDescriptor/StructuredSyntaxNameSuffix/index.ts
  src/library/ContentDescriptor/TopLevel/Any.ts
  src/library/ContentDescriptor/TopLevel/Composite/Any.ts
  src/library/ContentDescriptor/TopLevel/Composite/all.ts
  src/library/ContentDescriptor/TopLevel/Composite/exports.ts
  src/library/ContentDescriptor/TopLevel/Composite/index.ts
  src/library/ContentDescriptor/TopLevel/Discrete/Any.ts
  src/library/ContentDescriptor/TopLevel/Discrete/all.ts
  src/library/ContentDescriptor/TopLevel/Discrete/exports.ts
  src/library/ContentDescriptor/TopLevel/Discrete/index.ts
  src/library/ContentDescriptor/TopLevel/exports.ts
  src/library/ContentDescriptor/TopLevel/index.ts
  src/library/ContentDescriptor/index.ts
  src/library/MediaType/StructuredSyntaxNameSuffix/Any.ts
  src/library/MediaType/StructuredSyntaxNameSuffix/exports.ts
  src/library/MediaType/StructuredSyntaxNameSuffix/index.ts
  src/library/MediaType/TopLevel/Any.ts
  src/library/MediaType/TopLevel/Composite/Any.ts
  src/library/MediaType/TopLevel/Composite/exports.ts
  src/library/MediaType/TopLevel/Composite/index.ts
  src/library/MediaType/TopLevel/Discrete/Any.ts
  src/library/MediaType/TopLevel/Discrete/exports.ts
  src/library/MediaType/TopLevel/Discrete/index.ts
  src/library/MediaType/TopLevel/exports.ts
  src/library/MediaType/TopLevel/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/Image/index.ts
  src/library/customTypes/UniformResourceIdentifier/Data/index.ts
Labels: refactor

#499 refactor(library/ContentDescriptor): clarifies `serializableParameters` implementation
  src/library/ContentDescriptor/index.ts
Labels: refactor

#509 refactor(library/ShimmedStabilityAIClient): clarifies context of schemas
  src/library/ShimmedStabilityAIClient/index.ts
Labels: refactor

#510 linter(vitest): preps for first unit tests
  eslint.config.ts
  eslint.vitest.ts
Labels: linter

#515 refactor(library): flattens contents of "/customTypes" into parent
  src/features/TextToImage/config/utilities/DynamicConfig/EndpointResponseError.ts
  src/features/TextToImage/config/utilities/DynamicConfig/FetchingError.ts
  src/features/TextToImage/config/utilities/DynamicConfig/index.ts
  src/features/TextToImage/config/utilities/StaticConfig/StaticConfigReadingError.ts
  src/features/TextToImage/config/utilities/StaticConfig/index.ts
  src/features/TextToImage/models/SDXL/client/conversions/StabilityAI_Client_Image.ts
  src/features/TextToImage/types/Output/Image.ts
  src/features/TextToImage/webAPI/Server/ServerSpecificationError.ts
  src/library/Base64CharacterEncodedByteSequence/index.ts
  src/library/ContentDescriptor/index.ts
  src/library/HTTP/Client.ts
  src/library/NonTrivialString/ParsingError.ts
  src/library/NonTrivialString/index.ts
  src/library/ShimmedStabilityAIClient/index.ts
  src/library/StringSubset.ts
  src/library/URLComponent/URLOrigin.ts
  src/library/URLComponent/URLPath.ts
  src/library/URLComponent/index.ts
  src/library/UniformResourceIdentifier/Data/EncodingIdentifier/Any.ts
  src/library/UniformResourceIdentifier/Data/EncodingIdentifier/all.ts
  src/library/UniformResourceIdentifier/Data/EncodingIdentifier/exports.ts
  src/library/UniformResourceIdentifier/Data/EncodingIdentifier/index.ts
  src/library/UniformResourceIdentifier/Data/Image/Format/Any.ts
  src/library/UniformResourceIdentifier/Data/Image/Format/all.ts
  src/library/UniformResourceIdentifier/Data/Image/Format/exports.ts
  src/library/UniformResourceIdentifier/Data/Image/Format/index.ts
  src/library/UniformResourceIdentifier/Data/Image/index.ts
  src/library/UniformResourceIdentifier/Data/index.ts
  src/library/UniformResourceIdentifier/index.ts
Labels: refactor

#518 refactor(library/math): preps directory for tests
  src/library/Byte/utilities/cofactorTo.ts
  src/library/Range/index.ts
  src/library/math/aggregator/Aggregator.ts
  src/library/math/aggregator/arithmeticMeanOf.ts
  src/library/math/aggregator/index.ts
  src/library/math/aggregator/sumOf.ts
  src/library/math/aggregators.ts
  src/library/math/index.ts
  src/library/math/operator/constructive/cofactor.ts
  src/library/math/operator/constructive/greatestCommonDivisor.ts
  src/library/math/operator/constructive/index.ts
  src/library/math/operator/constructive/leastCommonMultiple.ts
  src/library/math/operator/index.ts
  src/library/math/operators.ts
Labels: refactor

#523 ci(dependabot): changes from auto-merge from "merge" to "squash"
  .github/workflows/dependabot.yml
Labels: ci

#527 refactor: highlights `name` overrides for `Error` subclasses
  src/features/TextToImage/config/utilities/DynamicConfig/EndpointResponseError.ts
  src/features/TextToImage/config/utilities/DynamicConfig/FetchingError.ts
  src/features/TextToImage/config/utilities/StaticConfig/StaticConfigReadingError.ts
  src/features/TextToImage/webAPI/Server/ServerConnectionError.ts
  src/features/TextToImage/webAPI/Server/ServerSpecificationError.ts
  src/library/Attempt/error/NonActionableError.ts
  src/library/Attempt/factory/AttemptCreationError.ts
  src/library/Base64/CharacterSequence/ConformanceError.ts
  src/library/Base64CharacterEncodedByteSequence/ParsingError.ts
  src/library/Byte/Sequence/EncodingCompatibilityError.ts
  src/library/HTTP/Endpoint/RequestError.ts
  src/library/HTTP/Endpoint/ResponseError.ts
  src/library/NonTrivialString/ParsingError.ts
  src/library/Parser/ParsingError.ts
  src/library/URLComponent/URLOrigin.ts
  src/library/URLComponent/URLPath.ts
Labels: refactor

#533 tests(library/math): applies template for functional suite to `greatestCommonDivisor`
  docs/setup/for_developers.md
  docs/testing/unit/development.md
  docs/testing/unit/seeds/about.md
  docs/testing/unit/seeds/functional.md
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
Labels: tests

#532 tests(library/math): stubs complete coverage for `greatestCommonDivisor`
  docs/testing/unit/seeds/functional.md
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
Labels: tests

#534 fix(library/math): guards against inoperable operands in `greatestCommonDivisor`
  docs/testing/unit/seeds/functional.md
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
  src/library/math/operator/constructive/greatestCommonDivisor.ts
  src/library/math/operator/index.ts
  src/library/math/operator/predicate/index.ts
  src/library/math/operator/predicate/isOperable.test.ts
  src/library/math/operator/predicate/isOperable.ts
Labels: fix

#540 prefeature(library/Attempt): lets `NonActionableError` conform to "constructable"
  src/library/Attempt/error/NonActionableError.ts
Labels: prefeature

#539 refactor(library/math): separates concerns of "number taxonomy" from `isOperable` test suite
  src/library/math/numberTaxonomy.ts
  src/library/math/operator/predicate/isOperable.test.ts
Labels: refactor

#543 tests(library/math): clarifies labels for `greatestCommonDivisor` suite
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
Labels: tests

#541 fix(library/math): guards against fractional operands in `greatestCommonDivisor`
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
  src/library/math/operator/constructive/greatestCommonDivisor.ts
  src/library/math/operator/predicate/index.ts
  src/library/math/operator/predicate/isWhole.test.ts
  src/library/math/operator/predicate/isWhole.ts
Labels: fix

#545 tests(library/math): completes spec for in-scope failure mode of `greatestCommonDivisor`
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
Labels: tests

#552 ci(node): triggers workflow for security updates
  .github/workflows/node.yml
Labels: ci

#555 chore(release): merges v0.3.0
  package-lock.json
  package.json
Labels: chore

#559 ci(node): allows short-circuited execution of workflow for non-node changes
  .github/workflows/node.yml
Labels: ci

#561 linter(markdown): enforces same set of rules as VSCode extension
  .github/workflows/docs.yml
  .markdownlint-cli2.yaml
  eslint.config.ts
  eslint.markdown.ts
  lint-staged.config.ts
  package-lock.json
  package.json
Labels: linter

#562 docs(ISSUE_TEMPLATE): refreshes "track-release"
  .github/ISSUE_TEMPLATE/track-release.md
  eslint.markdown.ts
Labels: docs

#563 docs(contributing): formalizes the expected format for commit messages
  docs/contributing/commit-messages.md
Labels: docs

#554 docs(setup/for_devs): adds example for specifying custom port
  docs/setup/for_developers.md
Labels: docs

#568 tests(library/math): specs operand order for `greatestCommonDivisor`
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
Labels: tests

#569 refactor(library/math): calls out assumed operand order in `greatestCommonDivisor`
  src/library/math/operator/constructive/greatestCommonDivisor.ts
Labels: refactor

#570 tests(library/math): specs handling of 0 in `greatestCommonDivisor`
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
Labels: tests

#571 tests(library/math): specs preservation of operand identity in `greatestCommonDivisor`
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
Labels: tests

#572 tests(library/math): specs how co-primes should be handled in `greatestCommonDivisor`
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
Labels: tests

#574 refactor(library/math): simplifies implementation in `greatestCommonDivisor`
  src/library/math/operator/constructive/greatestCommonDivisor.ts
Labels: refactor

#575 refactor(library/math): documents alternative terms for "greatest common divisor"
  src/library/math/operator/constructive/greatestCommonDivisor.test.ts
  src/library/math/operator/constructive/greatestCommonDivisor.ts
Labels: refactor

#580 fix(library/Range): enforces a semantic match for guard in `DiscreteRange.spanning(...)`
  src/library/Range/DiscreteRange.ts
Labels: fix

#584 ci(dependabot): enables auto-approval for patch bumps to `vue-tsc`
  .github/workflows/dependabot.yml
Labels: ci

#589 ci(dependabot): enables auto-approval for minor bumps to `eslint`
  .github/workflows/dependabot.yml
Labels: ci

#591 linter(import): enforces placement of "@/**" imports between external and internal imports
  eslint.import.ts
  src/features/TextToImage/components/TextToImageOutputAlert.vue
  src/features/TextToImage/models/SDXL/client/conversions/GenerateFromTextResponse.ts
  src/features/TextToImage/models/SDXL/client/index.ts
Labels: linter

#596 refactor(main): prefers absolute paths
  src/main.ts
Labels: refactor

#594 refactor: highlights files responsible for defining core module ideas
  src/components/DiscreteSlider.vue
  src/features/TextToImage/models/SDXL/client/conversions/StabilityAI_Client_Image.ts
  src/features/TextToImage/models/SDXL/client/index.ts
  src/features/TextToImage/types/Output/Image.ts
  src/features/TextToImage/types/Output/definition.ts
  src/features/TextToImage/types/index.ts
  src/library/Base64CharacterEncodedByteSequence/ParsingError.ts
  src/library/Base64CharacterEncodedByteSequence/definition.ts
  src/library/ContentDescriptor/definition.ts
  src/library/NonTrivialString/ParsingError.ts
  src/library/NonTrivialString/definition.ts
  src/library/Parser/definition.ts
  src/library/Parser/string/StringParser.ts
  src/library/Range/DiscreteRange.ts
  src/library/Range/definition.ts
  src/library/ShimmedStabilityAIClient/definition.ts
  src/library/URLComponent/URLOrigin.ts
  src/library/URLComponent/URLPath.ts
  src/library/UniformResourceIdentifier/Data/Image/definition.ts
  src/library/UniformResourceIdentifier/Data/definition.ts
  src/library/UniformResourceIdentifier/definition.ts
Labels: refactor

#599 linter(import): conforms config to precedent in package documentation
  eslint.import.ts
  package-lock.json
  package.json
Labels: linter

#608 refactor: avoids reaching directly into a namespace module's "definition"
  src/components/DiscreteSlider.vue
  src/features/TextToImage/models/SDXL/client/conversions/StabilityAI_Client_Image.ts
  src/features/TextToImage/models/SDXL/client/exports.ts
  src/features/TextToImage/types/Output/Image.ts
  src/features/TextToImage/types/Output/exports.ts
  src/features/TextToImage/types/exports.ts
  src/library/Base64CharacterEncodedByteSequence/ParsingError.ts
  src/library/Base64CharacterEncodedByteSequence/exports.ts
  src/library/ContentDescriptor/definition.ts
  src/library/ContentDescriptor/exports.ts
  src/library/NonTrivialString/ParsingError.ts
  src/library/NonTrivialString/exports.ts
  src/library/Parser/exports.ts
  src/library/Range/exports.ts
  src/library/ShimmedStabilityAIClient/definition.ts
  src/library/ShimmedStabilityAIClient/exports.ts
  src/library/URLComponent/URLOrigin.ts
  src/library/URLComponent/URLPath.ts
  src/library/UniformResourceIdentifier/Data/Image/definition.ts
  src/library/UniformResourceIdentifier/Data/Image/exports.ts
  src/library/UniformResourceIdentifier/Data/definition.ts
  src/library/UniformResourceIdentifier/definition.ts
Labels: refactor

#609 refactor: ensures all internal "definition" imports have explicit file extensions
  src/library/Parser/string/StringParser.ts
Labels: refactor
